version: "3"
services:
  app:
    restart: always
    build: .
    container_name: myweb
    volumes:
      - ".:/webapp"
    ports:
      - "8000:8000"
    command: ./start.sh
  db:
    image: mysql:5.7
    container_name: mydb
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=web_data
