# Generated by Django 2.2.4 on 2020-03-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=10)),
                ('relation', models.CharField(blank=True, max_length=10)),
                ('job', models.CharField(max_length=10)),
                ('both', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('both',),
            },
        ),
    ]
